#!/bin/bash
# Simple setup script for inneranimalmedia.com → iAccess
# Uses Cloudflare Dashboard method (recommended)

echo "🌐 Setting up inneranimalmedia.com for iAccess Platform"
echo ""
echo "📋 Configuration:"
echo "   Zone ID: 0bab48636c1bea4be4ea61c0c7787c3e"
echo "   Account ID: ede6590ac0d2fb7daf155b35653457b2"
echo "   Worker: iacess"
echo "   Domain: inneranimalmedia.com"
echo ""
echo "🚀 Setup Steps:"
echo ""
echo "1. Go to Workers Dashboard:"
echo "   https://dash.cloudflare.com/ede6590ac0d2fb7daf155b35653457b2/workers/services/view/iacess"
echo ""
echo "2. Click 'Triggers' tab"
echo ""
echo "3. Click 'Add Custom Domain'"
echo ""
echo "4. Enter: inneranimalmedia.com"
echo "   ✅ Check 'Override existing DNS records' if prompted"
echo "   Click 'Add Custom Domain'"
echo ""
echo "5. Repeat for www.inneranimalmedia.com"
echo ""
echo "✅ After setup, your iAccess platform will be available at:"
echo "   - https://inneranimalmedia.com/"
echo "   - https://www.inneranimalmedia.com/"
echo ""
echo "📋 All 13 pages will be accessible:"
echo "   - https://inneranimalmedia.com/ (Dashboard)"
echo "   - https://inneranimalmedia.com/analytics"
echo "   - https://inneranimalmedia.com/workers"
echo "   - https://inneranimalmedia.com/databases"
echo "   - https://inneranimalmedia.com/storage"
echo "   - https://inneranimalmedia.com/kv"
echo "   - https://inneranimalmedia.com/vectorize"
echo "   - https://inneranimalmedia.com/workflows"
echo "   - https://inneranimalmedia.com/queues"
echo "   - https://inneranimalmedia.com/email"
echo "   - https://inneranimalmedia.com/integrations"
echo "   - https://inneranimalmedia.com/settings"
echo "   - https://inneranimalmedia.com/ai-gateway"
echo "   - https://inneranimalmedia.com/browser-rendering"
echo ""
echo "⏳ SSL certificate will be issued automatically (1-5 minutes)"
echo "📊 All Pro zone features will be enabled"
